require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '12.0'

target 'MyApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'MyAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  if (!ENV['SKIP_FLIPPER'])
    use_flipper!({ 'Flipper' => '0.85.0' , 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1' })
  end

  post_install do |installer|
    react_native_post_install(installer)
  end

  use_unimodules!(exclude: [
    'expo-face-detector',
    'expo-constants',
    'expo-file-system',
    'expo-permissions',
    'expo-app-loader-provider',
    'unimodules-barcode-scanner-interface',
    'unimodules-camera-interface',
    'unimodules-constants-interface',
    'unimodules-face-detector-interface',
    'unimodules-file-system-interface',
    'unimodules-sensors-interface',
    'unimodules-task-manager-interface',
    'expo-image-loader',
    'unimodules-image-loader-interface',
    'unimodules-permissions-interface',
  ])
end